### ISSUE TITLE
Add Cosign signature verification support

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/image-rs#46]
As mentioned in https://github.com/confidential-containers/image-rs/issues/7, more new signing schemes need to be supported.

[Cosign](https://github.com/sigstore/cosign) is a good signing scheme, which uses ECDSA_P256_SHA256_ASN1 digital signature algorithm.The most advantage of cosign compared with simple signing is

**There is no need to store signature files like GPG, instead all signatures are stored in the same registry as the image. Thus we do NOT need to add extra signature files in the `rootfs` when preparing CCv0**

I think the main tasks to support cosign:
**Stage 1: Base features and Unit tests**
- [x] Prepare cosign-signed images for tests.
- [x] Implement cosign verification module
- [x] Documentation for the format of cosign in `policy.json`
- [x] Unit tests for cosign
https://github.com/confidential-containers/image-rs/pull/47

**Stage 2: Integration Tests**

- [x] Add public key resource to Attestation Agent's Sample KBC and Offline-Fs-Kbc, modify `policy.json` to enable cosign
https://github.com/confidential-containers/attestation-agent/pull/91
https://github.com/confidential-containers/attestation-agent/pull/95
- [x] Integration tests
https://github.com/confidential-containers/image-rs/pull/64
- [x] Add e2e test in kata-containers
https://github.com/kata-containers/tests/issues/5213

Above are for release `v0.2.0`

**Stage 3: More Features**
- [x] Add quickstart document in CoCo's documentation
https://github.com/confidential-containers/documentation/pull/65
- [ ] Support different kinds of ways to get public key, e.g. `kms`, `https` link, etc.
- [ ] Integration test using KMS

**Comment by Xynnn007** [comment]
I'd like to take this, after https://github.com/confidential-containers/image-rs/pull/45 is merged, because there may be integration tests based on it

**Comment by sameo** [comment]
@Xynnn007 I suppose you meant `Thus we do NOT need to add extra signature files in the rootfs when preparing CCv0` and not `Thus we do need to add extra signature files in the rootfs when preparing CCv0` ?

**Comment by Xynnn007** [comment]
> @Xynnn007 I suppose you meant `Thus we do NOT need to add extra signature files in the rootfs when preparing CCv0` and not `Thus we do need to add extra signature files in the rootfs when preparing CCv0` ?

Yes, thanks, sorry for the typo

**Comment by bodzhang** [comment]
> instead all signatures are stored in the same registry as the image

Is this referring to [Notary V2](https://github.com/notaryproject/notaryproject) and [ORAS](https://github.com/oras-project/oras) support in some of the cloud providers' container repos?

**Comment by Xynnn007** [comment]
> > instead all signatures are stored in the same registry as the image
> 
> Is this referring to [Notary V2](https://github.com/notaryproject/notaryproject) and [ORAS](https://github.com/oras-project/oras) support in some of the cloud providers' container registries?

Hi @bodzhang , thanks for the question. Sorry for not included any details about cosign. 

Cosign doesn't need the registrys to support Notary v2 or ORAS. In fact, the image's signature will be organized as an "image bundle" and pushed into the same repository with a tag generated due to the image digest. The algorithm to calculate the "image bundle"'s reference is deterministic. 

When it is time to verify an image's signature, what a cosign verifier actually do is to use the digest of the original image to calculate "image bundle"'s reference, and download the "image bundle" to extract signature, and then do the verification. These are all the principles behind cosign. This rational and interesting process is described in the [README.md](https://github.com/confidential-containers/image-rs/pull/47/files#diff-98b944311111ee03aa40743049bfa13234844d527916ff2d0e60a499c18ee162) under reviewing.

Some unit test cases are already included in [the same pr](https://github.com/confidential-containers/image-rs/pull/47/files#diff-5ee5d4073fc6d937c1153b7dd4bd91c60896a1fc7aa721e47cb4c6d76408da59R245), s.t. verifying a test signed image already pushed in `quay.io`, `dockerhub` and `aliyuncs.com` using a [given ed25519 public key](https://github.com/confidential-containers/image-rs/pull/47/files#diff-ae2b1069acb0da04037ebc7e4e242ad824304ac4d29681c810a32be57cb820c6). 

Please refer to [this official link](https://github.com/sigstore/cosign#registry-support) of cosign for the list of supported registry (which means we **DO NOT** need to add any extra configuration, just a cosign tool can help us push signed image and do verification).

**Comment by bodzhang** [comment]
@Xynnn007, thanks for the explanation. I added a comment to #7, calling for support for Notary V2/Notation.

**Comment by ariel-adam** [comment]
@Xynnn007 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by Xynnn007** [comment]
@ariel-adam Hi, this issue is still relevant. 

I think we want to add this in mid-November release, cc @peterzcst @arronwy @jialez0 

Still, this PR needs people help to review https://github.com/confidential-containers/image-rs/pull/47 to move forward cosign verification support.

**Comment by ariel-adam** [comment]
Cool, I've mapped it to the CoCo releases project, drop V0.2.0 priority medium

**Comment by Xynnn007** [comment]
Hi, after https://github.com/confidential-containers/image-rs/pull/47 is merged, I'll add integration test for cosign in image-rs. I'd like add only two cases:

* Accept a cosign-signed image from a protected registry with a right public key
* Deny an unsigned image from a protected registry

And both cases will use both `Sample-KBC` and `Offline-Fs-KBC` to get public key, thus there will be four (2 x 2) routines.

The four routines will only cover the function of cosign verification. Is this ok? @stevenhorsman @arronwy ?

**Comment by stevenhorsman** [comment]
Hey Ding, I'm really sorry that I missed this issue previously - cosign sounds great and having the signatures stored in the registry and not needing to add extra artifacts to the guest rootfs image sounds awesome. In terms of integration testing that sounds like a good start. The additional tests that we have for the simple signing are:
- Test that pulling an image from an unprotected registry works - I think this would be covered by existing tests in image-rs?
- Test that pulling an image from a protected registry that was signed with a different public key fails. This might be worth doing still as I think it would still apply if you passed the 'wrong' cosign.pub key from the attestation-agent?

Do you need any help in pushing some test images to our https://quay.io/repository/kata-containers/confidential-containers registry that we store the other container images in then let me know - I've seen that quay is a supported registry for co-sign.

Also - I'm guessing that your integration tests will go into image-rs, but I wonder if we want to consider adding them to the kata-containers repo for e2e testing, including maybe with the operator? If so we can get an issue created in kata-containers/tests and I can either get involved with the implementation, or point someone else to the existing tests and a place to add new ones.

I hope this helps a little, let me know if there are any follow questions, or comments and I'll do my best to respond quicker this time!

**Comment by Xynnn007** [comment]
Hey @stevenhorsman , thanks very much and happy to get your reply!


> * Test that pulling an image from an unprotected registry works - I think this would be covered by existing tests in image-rs?

Yes.




> * Test that pulling an image from a protected registry that was signed with a different public key fails. This might be worth doing still as I think it would still apply if you passed the 'wrong' cosign.pub key from the attestation-agent?

I'll add this case in the integration test in image-rs. 

Also, I will push a new test image in `quay.io/kata-containers/confidential-containers/cosign` and share the public key with you. Please help to add test in kata-containers for e2e testing, thanks!

**Comment by Xynnn007** [comment]
Close this issue. When getting public key from `kms` and `http` is needed, we can open other issues.
