### ISSUE TITLE
Add the ability to get container registry credentials from the attestation agent

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/image-rs#63]
### Description

We want to add the ability to support optional credentials when pulling image from authenticated registries that we get from the attestation_agent (via the KBC) in a similar way to how we flow the sigstore/policy/public GPG keys for signature verification.

image-rs already has the ability to pass authentication information on the pull request, so once https://github.com/confidential-containers/attestation-agent/issues/92 is implemented we just want to glue the capability together similar to how we read the signature files: https://github.com/confidential-containers/image-rs/blob/d60dc9c870eab93b3beb5d8f05ecde27b972c1b7/signature/src/agent.rs#L119

I think the best approach (rather than the `agent-rpc.rs` in kata having to access the attestation-agents getresource end point), is to update `pull_image`
https://github.com/confidential-containers/image-rs/blob/d60dc9c870eab93b3beb5d8f05ecde27b972c1b7/src/image.rs#L139-L145
to try and get the auth_info using the get_resource call if it’s not supplied on the request. This should be optional though. There are some registries that a completely public (like quay.io/confidential-containers repo we are using for the test images), some that are private and you can't get anything without credentials and then a gray area of things in between. For example any public repo in docker hub can be accessed without credentials, but as an anonymous IP you are limited to (~100 IIRC) requests a month, and after that need to log in to get more, so good get into a state that you can pull anonymously sometimes, not then get rejected later.
I think the best approach is to continue the logic we have in image-rs at the moment: Default to `let mut auth = RegistryAuth::Anonymous;` and credentials aren't mandatory, but we can attempt the get_resource request to try and get them and if they are supplied then we configure registry auth based on then.

**Comment by Xynnn007** [comment]
> I think the best approach is to continue the logic we have in image-rs at the moment: Default to `let mut auth = RegistryAuth::Anonymous;` and credentials aren't mandatory, but we can attempt the get_resource request to try and get them and if they are supplied then we configure registry auth based on then.

Hi, do you mean that while we pull an image from registry `A`, we try to get credential from the KBC via get_resource?

Besides, I found that https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md has defined an `auth.json` file, which exactly matches our needs here. Do we need to follow this?

**Comment by Xynnn007** [comment]
I'd like to take this.

### Goal

Implement `auth.json` support for image-rs.

### Roadmap

- [ ] Implement feature of `auth.json`
- [ ] Unit tests
- [ ] Prepare related resources on the AA side
- [ ] Integration tests using image-rs
